#!/bin/bash
#SBATCH --job-name=ds_lora
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=48G
#SBATCH --cpus-per-task=8
#SBATCH --time=12:00:00
#SBATCH --output=/project/dachxiu/afeng/prover/logs/deepseek_lora_%j.log
#SBATCH --error=/project/dachxiu/afeng/prover/logs/deepseek_lora_%j.log
#SBATCH --account=pi-dachxiu
#SBATCH --chdir=/project/dachxiu/afeng/prover

# LoRA fine-tune DeepSeek-Prover on miniF2F validation proofs.
# Requires data/deepseek_lora_train.jsonl (generated by run_deepseek_valid.sh).

module load python/3.11.9
module load cuda/12.1

source /project/dachxiu/afeng/prover/venv/bin/activate

export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export PATH="$HOME/.elan/bin:$HOME/.local/node16/bin:$PATH"
unset GITHUB_ACCESS_TOKEN
export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt
export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt

if [ ! -f data/deepseek_lora_train.jsonl ]; then
    echo "ERROR: data/deepseek_lora_train.jsonl not found. Run run_deepseek_valid.sh first."
    exit 1
fi

NTRAIN=$(wc -l < data/deepseek_lora_train.jsonl)
echo "=== LoRA training on $NTRAIN miniF2F validation proof pairs ==="

python3 training/finetune_deepseek.py \
    --model-path  models/pretrained/deepseek-prover-v1.5-rl \
    --train-data  data/deepseek_lora_train.jsonl \
    --output-dir  models/finetuned/deepseek_minif2f/ \
    --epochs      10 \
    --batch-size  2 \
    --grad-accum  8 \
    --lr          2e-4 \
    --lora-r      16 \
    --lora-alpha  32 \
    --max-length  2048 \
    --load-in-4bit

echo "=== LoRA training done. Adapter at models/finetuned/deepseek_minif2f/lora_adapter ==="
